# Generated by Django 3.0.1 on 2019-12-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes_personals',
            field=models.CharField(choices=[(' programación', ' programación '), ('Bases de Datos', 'Bases de Datos')], default=1, max_length=50, verbose_name='Gustos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_profile',
            field=models.ImageField(default=1, upload_to='media/profile/photos/', verbose_name='Imagen de Perfil'),
            preserve_default=False,
        ),
    ]
