# Generated by Django 3.0.1 on 2019-12-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20191223_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='root', verbose_name='Slig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='likes_personals',
            field=models.CharField(choices=[('Programación', ' Programación '), ('Bases de Datos', 'Bases de Datos')], max_length=50, verbose_name='Gustos'),
        ),
    ]
