# Generated by Django 3.0.1 on 2019-12-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.TextField(blank=True, max_length=16, null=True, verbose_name='Subtitulo'),
        ),
    ]
