# Generated by Django 3.0.1 on 2019-12-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Subtitulo'),
        ),
    ]
