# Generated by Django 3.0.1 on 2019-12-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_auto_20191223_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/article/photos/', verbose_name='Imagen para el articulo'),
        ),
    ]
