# Generated by Django 3.0.2 on 2020-02-03 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='slugs',
            field=models.SlugField(default=datetime.datetime(2020, 2, 3, 16, 42, 33, 74878, tzinfo=utc), verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
