# Generated by Django 3.0.2 on 2020-02-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200203_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slugs',
            new_name='slug',
        ),
    ]
